version: '3'

services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'your-256-bit-secretyour-256-bit-secret'
      MERCURE_SUBSCRIBER_JWT_KEY: 'your-256-bit-secretyour-256-bit-secret'

      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        anonymous

      Warning: Please be aware that hardcoding secrets and tokens directly in docker-compose files or application's configurations might not be a good practice as it adds vulnerability to your application. It is best practice to use docker-compose combined with environment variables to handle secrets. Allowing your application to read these secrets at runtime keeps your application's configuration simpler, and can allow for more flexibility in deploying across different environments. If your secrets are properly stored and managed, they increase the security of your application.
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config
volumes:
  mercure_data:
  mercure_config: